name: Markdown links checker
on:
  push:
    branches:
    - main
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        max-depth: 2
        config-file: 'mlc_config.json'
        file-path: './README.md'
        folder-path: '1.ProblemBackground, 2.SolutionBackground, 3.ViewsAndPerspectives, 4.ADRs'
